name: Linux
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
      - trunk
    paths:
      - '**.c'
      - 'meson.build'
      - '**linux.yml'
  pull_request:
    branches:
      - trunk
    paths:
      - '**.c'
      - 'meson.build'
      - '**linux.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Meson and Ninja
      run: pip install meson ninja

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y geany libgtk-3-dev

    - name: Configure Build with Meson
      run: meson setup builddir

    - name: Build
      run: ninja -C builddir
